server:
  port: 8088
spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/reactiveWeb
    username: postgres
    password: pass
  flyway:
    url: jdbc:postgresql://localhost:5432/reactiveWeb
    locations: classpath:db/migration
    user: postgres
    password: pass


jwt:
  password:
    encoder:
      secret: 1707846b9794937cbd0329a50f6adf4e5bab77835a
      iteration: 64
      keyLength: 256
  secret: g1707846b9794937cbd0329a50733274d676d60a850380f6adf4e5bab77835a2
  expiration: 3600
  issuer: HeadOfService